---

# Create a Stack on Cloud Formation or Update if name already exists
- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: ".venv/bin/python"
  pre_tasks:
    - include_vars: group_vars/all/credentials.yml
  roles:
    - { role: create_cf_stack }
